- name: Run balancer
  hosts: blnc
  become: true
  tasks:
    - name: Install common
      ansible.builtin.import_role:
        name: common-config-docker

    - name: Move eth2 to external zone
      ansible.builtin.shell: "firewall-cmd --zone=external --change-interface=eth2 --permanent"

    - name: Move eth1 to dmz zone
      ansible.builtin.shell: "firewall-cmd --zone=dmz --change-interface=eth1 --permanent"

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: Copy nginx config file
      ansible.builtin.copy:
        src: "nginx.conf"
        dest: "/home/vagrant/nginx.conf"
        owner: vagrant
        group: vagrant

    - name: Run balancer container
      community.docker.docker_container:
        name: balancer
        image: nginx:latest
        volumes:
          - "/home/vagrant/nginx.conf:/etc/nginx/conf.d/default.conf"
        state: started
        restart: true
        restart_policy: unless-stopped
        ports:
          - "80:80"
