- name: Run balancer
  hosts: blnc
  become: true
  tasks:
    - name: Install common
      ansible.builtin.import_role:
        name: common-config-docker

    - name: Copy nginx config file
      ansible.builtin.copy:
        src: "nginx.conf"
        dest: "/home/vagrant/nginx.conf"
        owner: vagrant
        group: vagrant

    - name: Run balancer container
      community.docker.docker_container:
        name: balancer
        image: nginx:latest
        volumes:
          - "/home/vagrant/nginx.conf:/etc/nginx/conf.d/default.conf"
        state: started
        restart: true
        restart_policy: unless-stopped
        ports:
          - "80:80"
