- name: Run balancer
  hosts: blnc
  become: true
  tasks:
    - name: Install common
      ansible.builtin.import_role:
        name: common-config-docker

    # --- Config firewalld

    - name: Move eth2 to external zone
      ansible.builtin.shell: "firewall-cmd --zone=external --change-interface=eth2 --permanent"

    - name: Move eth1 to dmz zone
      ansible.builtin.shell: "firewall-cmd --zone=dmz --change-interface=eth1 --permanent"

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    # --- Static routes to internal network

    - name: Add static route
      ansible.builtin.blockinfile:
        path: /etc/sysconfig/network-scripts/route-eth1
        create: true
        block: |
          10.10.1.0/24 via 192.168.1.101

    - name: Restart network service
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted


    # ---

    - name: Copy nginx config file
      ansible.builtin.copy:
        src: "nginx.conf"
        dest: "/home/vagrant/nginx.conf"
        owner: vagrant
        group: vagrant

    - name: Copy ssl certificate
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/vagrant/{{ item }}"
        owner: vagrant
        group: vagrant
      with_items:
        - otus.local.crt
        - otus.local.key

    - name: Run balancer container
      community.docker.docker_container:
        name: balancer
        image: nginx:latest
        volumes:
          - "/home/vagrant/nginx.conf:/etc/nginx/conf.d/default.conf"
          - "/home/vagrant/otus.local.crt:/etc/nginx/otus.local.crt"
          - "/home/vagrant/otus.local.key:/etc/nginx/otus.local.key"
        state: started
        restart: true
        restart_policy: unless-stopped
        ports:
          - "80:80"
          - "443:443"

- name: Run exporters
  hosts: blnc
  become: true
  tasks:
    - name: Install edge duckprom node
      ansible.builtin.import_role:
        name: nmix.duckprom
      vars:
        duckprom_dir: /opt/duckprom
        duckprom_grafana_host: 10.10.1.143
        duckprom_basic_auth_enabled: false
