- name: Mount data dir via nfs
  hosts: apps
  become: true
  vars:
    data_dir: /opt/cms/data
    nfs_server_ip: "10.10.1.142"
    nfs_server_data_dir: /opt/cms/data
  tasks:
    - name: Install nfs packages
      ansible.builtin.dnf:
        name:
          - nfs-utils
          - nfs4-acl-tools
        state: present

    - name: Mount an NFS volume
      ansible.posix.mount:
        src: "{{ nfs_server_ip }}:{{ nfs_server_data_dir }}"
        path: "{{ data_dir }}"
        state: mounted
        fstype: nfs
