- name: Promote slave host
  hosts: "{{ target | default('no_hosts') }}"
  become: true
  tasks:
    - name: Run promote command on database
      ansible.builtin.shell: "/usr/pgsql-14/bin/pg_ctl promote -D /var/lib/pgsql/14/data"
      become_user: postgres
