- name: Promote slave host
  hosts: "{{ target | default('no_hosts') }}"
  become: true
  tasks:
    - name: Move eth1 to internal zone
      ansible.builtin.shell: "/usr/pgsql-14/bin/pg_ctl promote -D /var/lib/pgsql/14/data"
      become_user: postgres

- name: Switch app on another database
  hosts: apps
  become: true
  vars:
    project_dir: "/opt/cms"
    db_ip: "10.10.1.131"
  tasks:
    - name: Replace config file for app
      ansible.builtin.template:
        src: env-local.j2
        dest: "{{ project_dir }}/.env-local"
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Restart app
      community.docker.docker_compose:
        project_src: "{{ project_dir }}"
        restarted: true
        services:
          - web
