---
- name: Config inetRouter
  hosts: all
  become: true

  tasks:
    - name: Install epel-release
      ansible.builtin.yum:
        name: epel-release

    # --- IP Tables

    - name: Install packages
      ansible.builtin.yum:
        name:
          - vim
          - traceroute
          - iptables
          - iptables-services
        state: present
        update_cache: true

    - name: Copy iptables config
      ansible.builtin.template:
        src: files/iptables
        dest: /etc/sysconfig/iptables
        owner: root
        group: root
        mode: "0600"

    - name: Start and enable iptables service
      ansible.builtin.service:
        name: iptables
        state: restarted
        enabled: true

    # --- Forwarding

    - name: Set up forward packages across routers
      ansible.builtin.sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present

    # --- Static route

    - name: Add static route
      ansible.builtin.blockinfile:
        path: /etc/sysconfig/network-scripts/route-eth1
        create: true
        block: |
          192.168.0.0/22 via 192.168.255.2
          192.168.255.4/30 via 192.168.255.2
          192.168.255.8/30 via 192.168.255.2

    - name: Restart network service
      ansible.builtin.systemd:
        name: network
        state: restarted

    - name: Restart network service
      ansible.builtin.systemd:
        name: network
        state: restarted
